### ISSUE TITLE
i like it very well !

### ISSUE THREAD

**Issue by peter100u** [pacifio/flutter_art#1]
Hello, can it be encapsulated as a processing or p5.js api? This way we can use it better

**Comment by pacifio** [comment]
I started to make something like this , see this project -> https://github.com/pacifio/flutter_p5
But unfortunately it didn't get enough attention by developers so I basically stopped maintaining it , I need contributors . If you are interested in contributing let me know !

**Comment by pacifio** [comment]
Since this is not clearly an issue in code I am closing it
